[project]
name = "qr-scanner"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "numpy>=2.1.1",
    "opencv-python>=4.10.0.84",
    "qreader>=3.14",
]
