FROM mcr.microsoft.com/vscode/devcontainers/base:bullseye

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update package list
RUN apt-get update && apt-get upgrade -y

# Install pkgx
RUN apt install curl -y
RUN curl https://pkgx.sh | sh

# Install packages
RUN pkgx install \
    node@20 \
    pnpm.io@9.4.0 \
    bore.pub \
    fish \
    npx \
    uv

# Install libs
RUN apt-get install \
    libgl1 \
    libglib2.0-0 \
    libzbar0 \
    -y

ENV fish_greeting ""
ENV NODE_OPTIONS "--experimental-websocket"
ENV QR_DECODE_SERVICE_PORT 1927
