version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ..:/yvees
    ports:
      - 5173:5173
      - 7777:7777
    command: sleep infinity
