FROM mcr.microsoft.com/vscode/devcontainers/base:bullseye

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Update package list
RUN apt-get update && apt-get upgrade -y

# Install pkgx
RUN apt install curl -y
RUN curl https://pkgx.sh | sh

# Install packages
RUN pkgx install \
    bun@1.1 \
    node

ENV PATH="~/.bun/bin:${PATH}"
